name: build
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: SetUp JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint-Check
        id: lintCheck
        run: ./gradlew ktlintCheck
      - name: UnitTest
        id: unitTest
        run: ./gradlew unitTest

      - name: Comment when Lint was Failed
        uses: peter-evans/create-or-update-comment@v2
        if: failure() && steps.lintCheck.outcome == 'failure'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :x: KtLint 체크가 필요합니다.
      - name: Comment When UnitTest Was Failed
        uses: peter-evans/create-or-update-comment@v2
        if: failure() && steps.unitTest.outcome == 'failure'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :x: UnitTest 체크가 필요합니다.
      - name: Comment When All Step Was Passed
        uses: peter-evans/create-or-update-comment@v2
        if: success()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :white_check_mark: 테스트 통과!
