name: conatiner-test-comment-trigger

on:
  issue_comment:
    types: [created]

env:
  TESTS: "all,s3"

jobs:
  container-test:
    runs-on: ubuntu-latest
    steps:
      - name: split
        run: |
            echo "OPTION=$(echo ${{github.event.comment.body}} | cut -d " " -f 2)" >> $GITHUB_ENV
      - name: check-option
        run: |
            echo ${{ env.OPTION }}
      - uses: actions/checkout@v2
      - name: SetUp JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: "Check Option is valid"
        if: ${{ !contains(env.TESTS,env.OPTION) }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :x: 정의되지 않은 ContainerTest 옵션입니다!
      - name: "test-all"
        if: ${{ env.OPTION == 'all' }}
        run: ./gradlew containerTest -i
      - name: "test-s3"
        if: ${{ env.OPTION  == 's3'}}
        run: ./gradlew containerTest -i
      - name: "failure notificaton"
        if: ${{ contains(env.TESTS,env.OPTION) && failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :x: 컨테이너 테스트를 실패하였습니다.
      - name: "success notificaton"
        if: ${{ contains(env.TESTS,env.OPTION)  && success() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :white_check_mark: 컨테이너 테스트를 통과하였습니다.


