name: conatiner-test-comment-trigger

on:
  issue_comment:
    types: [created]

env:
  TESTS: "all,s3"

jobs:
  split-input:
    if: ${{ startsWith(github.event.comment.body, '컨테이너')}}
    runs-on: ubuntu-latest
    steps:
      - name: split
        uses: jannekem/run-python-script-action@v1
        env:
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
          COMMENT_CONTENT: ${{ github.event.comment.body }}
        with:
          script: |
            import os
            
            input = '${{ github.event.comment.body }}'
            commands = input.split()
            
            env_file = os.getenv('GITHUB_ENV')
            with open(env_file, "a") as myfile:
            myfile.write('OPTION=%s'%(commands[1]))
  container-test:
    runs-on: ubuntu-latest
    needs: split-input
    steps:
      - name: "Check Option is valid"
        id: option-validation
        if: ${{ !contains(env.TESTS,env.OPTION) }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :x: 정의되지 않은 ContainerTest 옵션입니다!
      - uses: actions/checkout@v2
      - name: SetUp JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: "test-all"
        if: ${{env.OPTION }} == 'all'
        run: ./gradlew containerTest --continue
      - name: "test-s3"
        if: ${{env.OPTION}}== 's3'
        run: ./gradlew containerTest --continue
      - name: "failure notificaton"
        if: ${{ contains(env.TESTS,env.OPTION) && failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :x: 컨테이너 테스트를 실패하였습니다.
      - name: "success notificaton"
        if: ${{ contains(env.TESTS,env.OPTION)  && success() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :white_check_mark: 컨테이너 테스트를 통과하였습니다.


